### ISSUE TITLE
Caused by read integer field with correct value as "D" text

### ISSUE THREAD

**Issue by LaoTsing** [spring-projects-experimental/spring-boot-r2dbc#28]
```
Caused by: java.lang.NumberFormatException: For input string: "D"
 at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:?]
 at java.lang.Integer.parseInt(Integer.java:652) ~[?:?]
 at java.lang.Integer.parseInt(Integer.java:770) ~[?:?]
 at io.r2dbc.postgresql.codec.IntegerCodec.doDecode(IntegerCodec.java:60) ~[r2dbc-postgresql-1.0.0.M7.jar:?]
 at io.r2dbc.postgresql.codec.IntegerCodec.doDecode(IntegerCodec.java:31) ~[r2dbc-postgresql-1.0.0.M7.jar:?]
 at io.r2dbc.postgresql.codec.AbstractCodec.decode(AbstractCodec.java:64) ~[r2dbc-postgresql-1.0.0.M7.jar:?]
 at io.r2dbc.postgresql.codec.DefaultCodecs.decode(DefaultCodecs.java:92) ~[r2dbc-postgresql-1.0.0.M7.jar:?]
 at io.r2dbc.postgresql.PostgresqlRow.get(PostgresqlRow.java:83) ~[r2dbc-postgresql-1.0.0.M7.jar:?]
```

It is a bug?

**Comment by mp911de** [comment]
Thanks for report. This looks like an issue within the Postgres driver. Please retest with the lastest version 0.8.0.M8 and file a ticket at https://github.com/r2dbc/r2dbc-postgresql if the issue persists.

**Comment by LaoTsing** [comment]
if change version to 0.8.M8, then select from RdbcRepository down with next error:

`java.lang.IllegalStateException: Bound parameter count does not match parameters in SQL statement
	at io.r2dbc.postgresql.client.Binding.validate(Binding.java:138) ~[r2dbc-postgresql-0.8.0.M8.jar:?]
	at io.r2dbc.postgresql.ExtendedQueryPostgresqlStatement$Bindings.finish(ExtendedQueryPostgresqlStatement.java:208) ~[r2dbc-postgresql-0.8.0.M8.jar:?]
	at io.r2dbc.postgresql.ExtendedQueryPostgresqlStatement$Bindings.access$100(ExtendedQueryPostgresqlStatement.java:186) ~[r2dbc-postgresql-0.8.0.M8.jar:?]
	at io.r2dbc.postgresql.ExtendedQueryPostgresqlStatement.execute(ExtendedQueryPostgresqlStatement.java:167) ~[r2dbc-postgresql-0.8.0.M8.jar:?]
	at io.r2dbc.postgresql.ExtendedQueryPostgresqlStatement.execute(ExtendedQueryPostgresqlStatement.java:109) ~[r2dbc-postgresql-0.8.0.M8.jar:?]
	at io.r2dbc.postgresql.ExtendedQueryPostgresqlStatement.execute(ExtendedQueryPostgresqlStatement.java:36) ~[r2dbc-postgresql-0.8.0.M8.jar:?]
	at org.springframework.data.r2dbc.core.DefaultDatabaseClient$ExecuteSpecSupport.lambda$exchange$2(DefaultDatabaseClient.java:365) ~[spring-data-r2dbc-1.0.0.M2.jar:1.0.0.M2]
	at org.springframework.data.r2dbc.core.DefaultSqlResult$2.apply(DefaultSqlResult.java:80) ~[spring-data-r2dbc-1.0.0.M2.jar:1.0.0.M2]
	at org.springframework.data.r2dbc.core.DefaultSqlResult$2.apply(DefaultSqlResult.java:77) ~[spring-data-r2dbc-1.0.0.M2.jar:1.0.0.M2]
	at org.springframework.data.r2dbc.core.DefaultDatabaseClient.doInConnectionMany(DefaultDatabaseClient.java:1338) ~[spring-data-r2dbc-1.0.0.M2.jar:1.0.0.M2]
	at org.springframework.data.r2dbc.core.DefaultDatabaseClient.lambda$inConnectionMany$4(DefaultDatabaseClient.java:178) ~[spring-data-r2dbc-1.0.0.M2.jar:1.0.0.M2]`

**Comment by LaoTsing** [comment]
> ```
> Caused by: java.lang.NumberFormatException: For input string: "D"
>  at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:?]
>  at java.lang.Integer.parseInt(Integer.java:652) ~[?:?]
>  at java.lang.Integer.parseInt(Integer.java:770) ~[?:?]
>  at io.r2dbc.postgresql.codec.IntegerCodec.doDecode(IntegerCodec.java:60) ~[r2dbc-postgresql-1.0.0.M7.jar:?]
>  at io.r2dbc.postgresql.codec.IntegerCodec.doDecode(IntegerCodec.java:31) ~[r2dbc-postgresql-1.0.0.M7.jar:?]
>  at io.r2dbc.postgresql.codec.AbstractCodec.decode(AbstractCodec.java:64) ~[r2dbc-postgresql-1.0.0.M7.jar:?]
>  at io.r2dbc.postgresql.codec.DefaultCodecs.decode(DefaultCodecs.java:92) ~[r2dbc-postgresql-1.0.0.M7.jar:?]
>  at io.r2dbc.postgresql.PostgresqlRow.get(PostgresqlRow.java:83) ~[r2dbc-postgresql-1.0.0.M7.jar:?]
> ```
> 
> It is a bug?

it is a Mac OS, in the Ubuntu and Cent OS it working a fine
